[package]
name = "bevy_console"
version = "0.5.0"
edition = "2021"
authors = ["RichoDemus <git@richodemus.com>"]
homepage = "https://github.com/RichoDemus/bevy-console"
repository = "https://github.com/RichoDemus/bevy-console"
description = "dev console for bevy"
license = "MIT"
readme = "README.md"

[dependencies]
bevy = { version = "0.9", path = "../bevy", default-features = false }
bevy_console_derive = { path = "./bevy_console_derive", version = "0.4.0" }
bevy_console_parser = { path = "./bevy_console_parser", version = "0.4.0" }
bevy_egui = { path = "../bevy_egui" }

[dev-dependencies]
bevy = { version = "0.9", path = "../bevy" }

[workspace]
members = ["bevy_console_derive", "bevy_console_parser"]
